name: Build

on: push

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v2
              with:
                  distribution: 'temurin'
                  java-version: '17'
            - uses: actions/cache@v2
              with:
                  path: ~/.m2/repository
                  key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                  restore-keys: |
                      ${{ runner.os }}-maven-
            - run: |
                  java -version
                  echo $JAVA_HOME
            - run: ./mvnw verify
            - uses: codecov/codecov-action@v1
              with:
                  token: ${{ 52a84b7e-3a2f-4cb9-8b01-b45816f7191f }}

